version: '3'

volumes:
  pg_data:
  static:
  media:
  redoc:


services:

  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .envdocker
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .envdocker
    volumes:
      - static:/backend_static
      - media:/app/media
      - redoc:/app/docs
    depends_on:
      - db

  frontend:
    env_file: .envdocker
    image: inferno681/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: nginx:1.19.3
    env_file: .envdocker
    ports:
      - 7000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - media:/app/media
      - static:/static
      - redoc:/usr/share/nginx/html/api/docs
    depends_on:
      - backend
