version: '3'

volumes:
  pg_data:
  static:
  media:
  redoc:


services:

  db:
    image: postgres:13
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: inferno681/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: inferno681/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: inferno681/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
