# Generated by Django 3.2.16 on 2023-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231210_1148'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_recipe(favorites)',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_user_recipe(shoppinglists)',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe(favorite)'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe(shoppinglist)'),
        ),
    ]
